{{- $replicaCount := index .Values "apiReplicaCount" -}}
{{ if (eq .Values.werf.env "dev") }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Chart.Name }}-api
  labels:
    app: {{ .Chart.Name }}-api
spec:
  replicas: 1
  serviceName: {{ .Chart.Name }}-api
  selector:
      matchLabels:
        app: {{ .Chart.Name }}-api
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}-api
    spec:
      containers:
      - name: {{ .Chart.Name }}-api
        image: '{{ index .Values.werf.image (printf "%s-api" .Chart.Name) }}'
        env:
        - name: PROJECT
          value: {{ .Chart.Name }}
        envFrom:
        - configMapRef:
            name: {{ .Chart.Name }}-common-config
        volumeMounts:
        - mountPath: /workspace
          name: workspace
        - name: id-rsa-vcs
          mountPath: "/root/.ssh/id_rsa"
          subPath: "id_rsa"  
      volumes:
        - name: workspace
          persistentVolumeClaim:
            claimName:  {{ .Chart.Name }}-api-pv-claim
        - name: id-rsa-vcs
          secret:
            secretName: id-rsa-vcs
            defaultMode: 0600
{{ end }}
