basePath: /api
tags:
  - name: auth
    description: Auth API
  - name: users
    description: "User API"
  - name: endpoints
    description: "Endpoint API"
  - name: docker
    description: "Docker API"
# components:
#   securitySchemes:
#     bearerAuth:
#       type: http
#       scheme: bearer
#       bearerFormat: JWT
#
# security:
#   - bearerAuth: []

# definitions
definitions:
  users:
    type: object
    required:
      - email
      - password
    properties:
      id:
        type: integer
        description: user Id
      email:
        type: string
        description: user Email
      password:
        type: string
        description: user Password
schemes:
  - https
  - http
