basePath: /api

schemes:
  - https
  - http

tags:
  - name: auth
    description: Auth API
  - name: users
    description: "User API"
  - name: endpoints
    description: "Endpoint API"
  - name: docker
    description: "Docker API"

securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header

# definitions
definitions:
  users:
    type: object
    required:
      - email
      - password
    properties:
      id:
        type: integer
        description: user Id
      email:
        type: string
        description: user Email
      password:
        type: string
        description: user password
