base_path: ./packages
base_url: 'https://api.crowdin.com'
preserve_hierarchy: true
files:
  - source: /sight-frontend/src/locale/en.js
    translation: /sight-frontend/src/locale/%two_letters_code%.js
