base_path: .
base_url: 'https://api.crowdin.com'
preserve_hierarchy: true
files:
  - source: /packages/sight-frontend/src/locale/en.json
    translation: /packages/sight-frontend/src/locale/%two_letters_code%.json
