version: '3.8'

services:
  app:
    image: globalartltd/node:22
    container_name: vms-app
    working_dir: /workspace
    volumes:
      - ..:/workspace
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DB_HOST=database
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=postgres
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - database
    command: ["sleep", "infinity"]

  database:
    image: postgres:17
    container_name: vms-postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
