{{ if (eq .env "dev") }}
---
image: base-node-image
from: node:20
docker:
  WORKDIR: /workspace/
  USER: root
  EXPOSE: "80"
  CMD: ["/bin/sleep", "infinity"]
ansible:
  install:
  - name: Setting up ssh
    shell: |
      printf "Host github.com\n\tStrictHostKeyChecking no\n\tUserKnownHostsFile=/dev/null\n" >> /etc/ssh/ssh_config
  - name: "Install PNPM"
    shell: npm -g i pnpm
  - name: "Install additional packages"
    apt:
      state: present
      update_cache: yes
      pkg:
        - locales
        - mc
        - vim
        - nano
        - telnet
        - neovim
        - git
---
{{ end }}