---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-backend
  labels:
    app: {{ .Chart.Name }}-backend
spec:
  selector:
    app: {{ .Chart.Name }}-backend
  ports:
  - name: {{ .Chart.Name }}-backend
    port: 80
    protocol: TCP